inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/MissingCopEnableDirective:
  Exclude:
    - "**/*_test.rb"

Metrics/ClassLength:
  Exclude:
    - "**/*_test.rb"

Metrics/MethodLength:
  Exclude:
    - "**/*_test.rb"

Metrics/LineLength:
  IgnoreCopDirectives: true
  Exclude:
    - "**/*_test.rb"
